default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: friendly_csv_dev

test:
  <<: *default
  database: friendly_csv_test

production:
  <<: *default
  database: friendly_csv_prod
